### ISSUE TITLE
Wrapping string children in ui-text may not be desirable

### ISSUE THREAD

**Issue by lurodrigo** [fulcrologic/fulcro-native#1]
Hi! First of all, thanks for the great work you've been doing. I've been learning about fulcro and react native for a few weeks. I managed to make my working app based on the skeleton you've provided a few days ago at [fulcro-expo-template](https://github.com/awkay/fulcro-expo-template). One diference between then and now is that `partial-element` did not wrap strings in `ui-text`, as `react-factory` does now. 

This may not be desirable when dealing with external libraries. For instance, I'm using [UI Kitten](https://github.com/akveo/react-native-ui-kitten), which provides its custom [Button](https://akveo.github.io/react-native-ui-kitten/docs/components/button/overview#button) component.  While React Native's `Button` takes its text from its `title` props, UI Kitten's uses its child string. So it works with `partial-element` but not with `react-factory`.

I'm not attaching a PR because this is kind of a soft issue, but an alternative would be to implement this behavior only on some specific components (not sure which ones, since I'm not using React Native's default components either).

Thanks!

**Comment by awkay** [comment]
Reasonable observation...probably need two diff factories.

**Comment by awkay** [comment]
Thanks...0.0.5-SNAPSHOT has a fix:  It allows an option map where you can specify `:ui-text false` to indicate no wrapping, or send a function if you need to use an alternate (like Native Base needs).
