### ISSUE TITLE
Does not work with Expo SDK 40 and up

### ISSUE THREAD

**Issue by andrerichards** [fulcrologic/fulcro-native#5]
Expo SDK 40 made a breaking change by moving AppLoading to a different package. 

See https://blog.expo.io/expo-sdk-40-is-now-available-d4d73e67da33 : AppLoading has been extracted from the expo package

This results in the following error when app starts up:

```
Exception

The following APIs have moved to separate packages and importing them from the "expo" package is no longer supported: AppLoading.

1. Add correct versions of these packages to your project

using:

expo install expo-app-loading

2. Change your imports so they use specific packages instead of the "expo" package:

-import { AppLoading} from 'expo-> import AppLoading.

from expo-app-loading'
```

I implemented a workaround/fix for this here:
https://github.com/andrerichards/fulcro-native/commit/b9cc506fbe5534043d950e997b337ebbe5a96f97

I added new namespaces `expo_application_40.cljc` and `expo_assets_40.cljc` as updating the current namespaces would break code that use SDK pre v40. I can open a pull request for this if you like.

**Comment by awkay** [comment]
A PR would be great.

**Comment by dlbears** [comment]
is this closed?

**Comment by awkay** [comment]
I guess so. Thanks.
